### ISSUE TITLE
Pressing Create Account button does not lead to Map Screen

### ISSUE THREAD

**Issue by msandare** [CMPUT301W20T27/BUber#21]
![create account button](https://user-images.githubusercontent.com/44533199/76367648-44db0200-62f3-11ea-9ea5-4ba33542f650.PNG)
When the Create Account button is pressed on the create account screen, it does not redirect the user to a new page. 
- Note: Best new page is likely Map Screen

**Comment by evantimms** [comment]
Can you make a ticket for this please, if you have time and can push a change go ahead

**Comment by nickroxcks** [comment]
Interesting. I don't seem to have this issue. Have you pulled the latest master code?

**Comment by msandare** [comment]
Weird. I've tried pulling but the same thing still happens.

**Comment by nickroxcks** [comment]
Just tested an it seems to work on my end. Maybe open the logs to see whats going on tbh.

**Comment by LukeDelaCruz** [comment]
Doesn't happen to me, but i did notice something interesting: 
![image](https://user-images.githubusercontent.com/32045517/76372419-f0d81980-6302-11ea-81fc-d2546448a4fe.png)
No internet my friend?

**Comment by msandare** [comment]
I figured it out! There was an issue with my AVD manager, I cold booted it and now it's working
